import {Suspense} from 'react';
import {notFound} from 'next/navigation';
import type {Metadata} from 'next';
import {Lang,tr,company} from '@/lib/company';
import {products,getCategory} from '@/lib/catalog';
import {Home,About,Information,ProductDetail,ContactDetails,Legal} from '@/components/site/pages';
import {PageHero} from '@/components/site/shared';
import {Catalogue} from '@/components/site/catalogue';
import {QuoteForm} from '@/components/site/quote-form';
type Props={params:Promise<{lang:Lang;path?:string[]}>};
const titles:Record<string,[string,string]>={about:['About us','من نحن'],products:['Product catalogue','كتالوج المنتجات'],industries:['Industries we serve','القطاعات التي نخدمها'],coverage:['Saudi Arabia coverage','نطاق التغطية'],brands:['Brand portfolio','العلامات التجارية'],clients:['Client relationships','علاقات العملاء'],procurement:['Procurement & supply','المشتريات والتوريد'],quality:['Quality & compliance','الجودة والامتثال'],contact:['Contact us','تواصل معنا'],'request-quote':['Request a quotation','اطلب عرض سعر'],privacy:['Privacy notice','إشعار الخصوصية'],terms:['Website terms','شروط الموقع'],cookies:['Cookie information','ملفات الارتباط']};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {lang,path=[]}=await params;const p=path[2]?products.find(p=>p.slug===path[2]):undefined;const c=path[1]?getCategory(path[1]):undefined;const title=p?.name||(c?(lang==='ar'?c.ar:c.name):titles[path[0]]?.[lang==='ar'?1:0])||tr(lang,'Trading & distribution in Saudi Arabia','التجارة والتوزيع في المملكة العربية السعودية');const pathname=path.length?'/'+path.join('/'):'';return {title,description:p?`${p.name} — B2B product enquiry from Faizan Al Rabee, Saudi Arabia.`:company.description,alternates:{canonical:`/${lang}${pathname}`,languages:{en:`/en${pathname}`,ar:`/ar${pathname}`}}}}
export default async function Page({params}:Props){const {lang,path=[]}=await params;const [page,cat,slug]=path;if(path.length>3)notFound();if(!page)return <><Home lang={lang}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Organization',name:company.name,url:company.origin,email:company.email,telephone:company.phone,address:{'@type':'PostalAddress',addressLocality:'Riyadh',addressCountry:'SA'},areaServed:'Saudi Arabia'})}}/></>;if(page==='products'){if(cat&&!getCategory(cat))notFound();if(slug){const p=products.find(p=>p.slug===slug&&p.category===cat);if(!p)notFound();return <ProductDetail lang={lang} product={p}/>}const c=cat?getCategory(cat):undefined;return <><PageHero lang={lang} title={c?(lang==='ar'?c.ar:c.name):tr(lang,'The right supplies, all in one place.','الاحتياجات المناسبة في مكان واحد.')} description={tr(lang,'Explore food, FMCG and general supplies. Find what you need, then ask us for a tailored quotation.','استكشف الأغذية والسلع الاستهلاكية والمستلزمات العامة. اعثر على احتياجاتك واطلب عرض سعر مخصصاً.')} section={tr(lang,'Product catalogue','كتالوج المنتجات')}/><Suspense fallback={<div className="wrap section">{tr(lang,'Loading catalogue…','جارٍ تحميل الكتالوج…')}</div>}><Catalogue lang={lang} category={cat}/></Suspense></>};if(path.length>1)notFound();if(page==='about')return <About lang={lang}/>;if(['coverage','brands','industries','clients','procurement','quality'].includes(page))return <Information lang={lang} page={page}/>;if(['privacy','terms','cookies'].includes(page))return <Legal lang={lang} page={page}/>;if(page==='contact'||page==='request-quote')return <><PageHero lang={lang} title={page==='contact'?tr(lang,'Let’s start a conversation.','لنبدأ المحادثة.'):tr(lang,'Tell us what you need.','أخبرنا بما تحتاج.')} description={tr(lang,'Share your requirements, quantities and delivery city. Include more than one product to keep your enquiry together.','شارك المتطلبات والكميات ومدينة التسليم. يمكنك إضافة أكثر من منتج في استفسار واحد.')} section={tr(lang,'Business enquiry','استفسار تجاري')}/><div className="wrap quote-layout"><Suspense fallback={<p>{tr(lang,'Loading form…','جارٍ تحميل النموذج…')}</p>}><QuoteForm lang={lang}/></Suspense><ContactDetails lang={lang}/></div></>;notFound()}
