'use client';
import {useState,useMemo,useEffect} from 'react';
import {useSearchParams} from 'next/navigation';
import {Search,SlidersHorizontal,ChevronLeft,ChevronRight} from 'lucide-react';
import {products,categories,brands} from '@/lib/catalog';
import {Lang,tr} from '@/lib/company';
import {ProductCard} from './shared';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Pagination,PaginationContent,PaginationItem,PaginationLink} from '@/components/ui/pagination';
export function Catalogue({lang,category='all'}:{lang:Lang;category?:string}){const query=useSearchParams();const [search,setSearch]=useState(query.get('q')||'');const [cat,setCat]=useState(category);const [brand,setBrand]=useState(query.get('brand')||'all');const [type,setType]=useState(query.get('type')||'all');const [page,setPage]=useState(1);const [open,setOpen]=useState(false);
useEffect(()=>{setCat(category)},[category]);
const filtered=useMemo(()=>products.filter(p=>(cat==='all'||p.category===cat)&&(brand==='all'||p.brand===brand)&&(type==='all'||p.type===type)&&(`${p.searchableKeywords} ${categories.find(c=>c.id===p.category)?.ar||''}`).toLowerCase().includes(search.toLowerCase().trim())),[cat,brand,type,search]);const pages=Math.ceil(filtered.length/18);const current=Math.min(page,Math.max(1,pages));
useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(t:unknown)=>void;unregisterTool:(n:string)=>void}}).modelContext;if(!context)return;context.registerTool({name:'search_catalogue',description:'Search and filter the visible Faizan Al Rabee product catalogue. Does not submit enquiries.',inputSchema:{type:'object',properties:{query:{type:'string'},category:{type:'string',enum:['all',...categories.map(c=>c.id)]},type:{type:'string',enum:['all','Food','Non-Food']}},required:['query']},execute:async(args:{query:string;category?:string;type?:string})=>{setSearch(args.query);setCat(args.category||'all');setType(args.type||'all');setBrand('all');setPage(1);return {content:[{type:'text',text:'Catalogue filters updated in the visible interface.'}]}}});return()=>context.unregisterTool('search_catalogue')},[]);
const reset=()=>{setSearch('');setCat('all');setBrand('all');setType('all');setPage(1)};
const filters=<><div className="filter-section"><h3>{tr(lang,'Product range','مجموعة المنتجات')}</h3><Select value={type} onValueChange={v=>{setType(v);setPage(1)}} dir={lang==='ar'?'rtl':'ltr'}><SelectTrigger className="filter-select" aria-label={tr(lang,'Product range','مجموعة المنتجات')}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{tr(lang,'All products','كل المنتجات')}</SelectItem><SelectItem value="Food">{tr(lang,'Food & beverages','الأغذية والمشروبات')}</SelectItem><SelectItem value="Non-Food">{tr(lang,'Non-food supplies','المستلزمات غير الغذائية')}</SelectItem></SelectContent></Select></div><div className="filter-section"><h3>{tr(lang,'Categories','الفئات')}</h3><button className={'category-filter '+(cat==='all'?'current':'')} onClick={()=>{setCat('all');setPage(1)}}>{tr(lang,'All categories','كل الفئات')}</button>{categories.map(c=><button key={c.id} className={'category-filter '+(cat===c.id?'current':'')} onClick={()=>{setCat(c.id);setPage(1)}}>{lang==='ar'?c.ar:c.name} <small>({c.count})</small></button>)}</div><div className="filter-section"><h3>{tr(lang,'Brand','العلامة التجارية')}</h3><Select value={brand} onValueChange={v=>{setBrand(v);setPage(1)}}><SelectTrigger className="filter-select" aria-label={tr(lang,'Brand','العلامة التجارية')}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{tr(lang,'All brands','كل العلامات')}</SelectItem>{brands.map(b=><SelectItem value={b} key={b}>{b}</SelectItem>)}</SelectContent></Select></div><button className="textlink" onClick={reset}>{tr(lang,'Clear all filters','مسح عوامل التصفية')}</button></>;
return <div className="wrap catalog-layout"><aside className="filters">{filters}</aside><div><div className="searchbar"><Search size={20}/><input aria-label={tr(lang,'Search products','البحث عن المنتجات')} placeholder={tr(lang,'Search a product, brand or pack size…','ابحث عن منتج أو علامة تجارية أو حجم عبوة…')} value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/>{search&&<button aria-label={tr(lang,'Clear search','مسح البحث')} onClick={()=>setSearch('')}>×</button>}</div><div className="catalog-toolbar"><span role="status">{filtered.length.toLocaleString(lang)} {tr(lang,'products','منتجاً')} · {tr(lang,'Availability confirmed on enquiry','يتم تأكيد التوفر عند الاستفسار')}</span><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><button className="small-btn mobile-filter"><SlidersHorizontal size={17}/>{tr(lang,'Filters','تصفية')}</button></SheetTrigger><SheetContent side={lang==='ar'?'right':'left'} style={{overflowY:'auto'}}><SheetHeader><SheetTitle>{tr(lang,'Filter products','تصفية المنتجات')}</SheetTitle><SheetDescription>{tr(lang,'Find the supplies your business needs.','اعثر على احتياجات أعمالك.')}</SheetDescription></SheetHeader><div style={{padding:24}}>{filters}<button className="btn" onClick={()=>setOpen(false)} style={{marginTop:25}}>{tr(lang,'Show products','عرض المنتجات')}</button></div></SheetContent></Sheet></div>{filtered.length?<><div className="product-grid">{filtered.slice((current-1)*18,current*18).map(p=><ProductCard key={p.id} product={p} lang={lang}/>)}</div><div className="pagination-area"><small>{tr(lang,`Page ${current} of ${pages}`,`الصفحة ${current} من ${pages}`)}</small><Pagination aria-label={tr(lang,'Product pages','صفحات المنتجات')}><PaginationContent><PaginationItem><button className="small-btn" disabled={current===1} aria-label={tr(lang,'Previous page','الصفحة السابقة')} onClick={()=>setPage(current-1)}><ChevronLeft size={18}/></button></PaginationItem>{Array.from({length:Math.min(5,pages)},(_,i)=>Math.max(1,Math.min(current-2,pages-4))+i).map(n=><PaginationItem key={n}><PaginationLink href="#main" isActive={current===n} onClick={e=>{e.preventDefault();setPage(n);document.getElementById('main')?.scrollIntoView()}}>{n}</PaginationLink></PaginationItem>)}<PaginationItem><button className="small-btn" disabled={current===pages} aria-label={tr(lang,'Next page','الصفحة التالية')} onClick={()=>{setPage(current+1);document.getElementById('main')?.scrollIntoView()}}><ChevronRight size={18}/></button></PaginationItem></PaginationContent></Pagination></div></>:<div className="empty"><h3>{tr(lang,'No matching products','لم نعثر على منتجات مطابقة')}</h3><p>{tr(lang,'Try a different search or clear your filters. You can also request an item outside the catalogue.','جرّب بحثاً آخر أو امسح التصفية. يمكنك أيضاً طلب منتج خارج الكتالوج.')}</p><button className="btn" style={{marginTop:22}} onClick={reset}>{tr(lang,'Reset filters','إعادة ضبط التصفية')}</button></div>}</div></div>}
