'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useState} from 'react';
import {Menu,ArrowUpRight,ChevronDown} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetTrigger,SheetClose} from '@/components/ui/sheet';
import {company,Lang,tr,href} from '@/lib/company';
import categories from '@/data/categories.json';
export function Brand({lang}:{lang:Lang}){return <Link href={href(lang)} className="brand" aria-label={company.name}><span className="brand-symbol" aria-hidden="true"><img src="/images/company-logo.png" alt="" width="1254" height="1254" /></span><span className="brand-name">{tr(lang,'FAIZAN AL RABEE','فيضان الربيع')}<small>{tr(lang,'TRADING & DISTRIBUTION','التجارة والتوزيع')}</small></span></Link>}
export function Header({lang}:{lang:Lang}){const path=usePathname();const [open,setOpen]=useState(false);const nav=[['','Home','الرئيسية'],['/about','About','من نحن'],['/products','Products','المنتجات'],['/industries','Industries','القطاعات'],['/coverage','Coverage','التغطية'],['/brands','Brands','العلامات'],['/quality','Quality','الجودة'],['/contact','Contact','تواصل معنا']];return <><div className="topbar"><div className="wrap"><span>{tr(lang,'YOUR BUSINESS. OUR COMMITMENT.','أعمالكم. التزامنا.')}</span><span>{tr(lang,'Food, FMCG & general supply across Saudi Arabia','الأغذية والسلع الاستهلاكية والتوريد العام في السعودية')}</span></div></div><header className="site-header"><div className="wrap header-row"><Brand lang={lang}/><nav aria-label={tr(lang,'Main navigation','القائمة الرئيسية')} className="desktop-nav">{nav.map(([url,en,ar])=>url==='/products'?<details className="nav-products" key={url}><summary>{tr(lang,en,ar)}<ChevronDown size={13}/></summary><div className="mega"><div><h3>{tr(lang,'A broader supply portfolio.','مجموعة أوسع من المنتجات.')}</h3><p style={{marginTop:12}}>{tr(lang,'Everyday essentials. Business-scale supply.','الاحتياجات اليومية بكميات تناسب الأعمال.')}</p><Link href={href(lang,'/products')} onClick={e=>e.currentTarget.closest('details')?.removeAttribute('open')} className="textlink">{tr(lang,'Browse all products','تصفح جميع المنتجات')}<ArrowUpRight size={16}/></Link></div><div className="mega-links">{categories.map(c=><Link key={c.id} href={href(lang,'/products/'+c.id)} onClick={e=>e.currentTarget.closest('details')?.removeAttribute('open')}>{lang==='ar'?c.ar:c.name}</Link>)}</div></div></details>:<Link className={path===href(lang,url)?'active':''} href={href(lang,url)} key={url}>{tr(lang,en,ar)}</Link>)}</nav><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><button className="mobile-menu" aria-label={tr(lang,'Open menu','فتح القائمة')} style={{border:0,background:'none',padding:7}}><Menu size={24}/></button></SheetTrigger><SheetContent side={lang==='ar'?'left':'right'}><SheetTitle className="p-6">{tr(lang,'Explore Faizan Al Rabee','استكشف فيضان الربيع')}</SheetTitle><div className="sheet-links">{nav.map(([url,en,ar])=><SheetClose asChild key={url}><Link href={href(lang,url)}>{tr(lang,en,ar)}</Link></SheetClose>)}<SheetClose asChild><Link className="btn" href={href(lang,'/request-quote')}>{tr(lang,'Request a quote','اطلب عرض سعر')}</Link></SheetClose></div></SheetContent></Sheet><Link className="language" href={path.replace(/^\/(en|ar)/,lang==='en'?'/ar':'/en')} aria-label={lang==='en'?'Switch to Arabic':'Switch to English'}>{lang==='en'?'العربية':'EN'}</Link><Link href={href(lang,'/request-quote')} className="btn header-cta">{tr(lang,'Request a quote','اطلب عرض سعر')}<ArrowUpRight size={15}/></Link></div></header></>}
