import Link from 'next/link';
import Image from 'next/image';
import {ArrowRight,ArrowUpRight,Package,ChevronRight,ShieldCheck,Handshake,Boxes,Headphones} from 'lucide-react';
import {Lang,tr,href,company} from '@/lib/company';
import {Category,Product,getCategory} from '@/lib/catalog';
export function Arrow({size=18}:{size?:number}){return <ArrowRight size={size} className="arrow"/>}
export function CTA({lang}:{lang:Lang}){return <section className="wrap section"><div className="cta-band"><div><div className="eyebrow">{tr(lang,'LET’S WORK TOGETHER','لنعمل معاً')}</div><h2>{tr(lang,'Your next requirement. Our next priority.','احتياجكم القادم. أولويتنا القادمة.')}</h2><p>{tr(lang,'Tell us what your business needs. We’ll take it from there.','أخبرونا بما تحتاجه أعمالكم، ودعوا الباقي لفريقنا.')}</p></div><Link href={href(lang,'/request-quote')} className="btn">{tr(lang,'Request a quote','اطلب عرض سعر')}<Arrow/></Link></div></section>}
export function PageHero({lang,title,description,section='Company'}:{lang:Lang;title:string;description:string;section?:string}){return <section className="page-hero"><div className="wrap"><div className="breadcrumbs"><Link href={href(lang)}>{tr(lang,'Home','الرئيسية')}</Link><ChevronRight size={14}/><span>{section}</span></div><div className="eyebrow">{tr(lang,'FAIZAN AL RABEE COMPANY','شركة فيضان الربيع')}</div><h1>{title}</h1><p>{description}</p></div></section>}
export function CategoryCard({category:c,lang}:{category:Category;lang:Lang}){const photo=c.type==='Non-Food';return <Link className="category-card" href={href(lang,'/products/'+c.id)}><div className={'category-image'+(photo?' photo':'')}>{c.image?<Image src={c.image} alt={lang==='ar'?c.ar:c.name} fill sizes="(max-width:680px) 44vw, 280px"/>:photo?<Image src="/images/hospitality.png" alt={lang==='ar'?c.ar:c.name} fill sizes="280px"/>:<div className="missing-photo" style={{display:'grid',placeItems:'center',height:'100%'}}><Package size={45} color="#84977a"/></div>}</div><div className="category-content"><h3>{lang==='ar'?c.ar:c.name}</h3><p><span>{c.count} {tr(lang,'catalogue items','منتجاً في الكتالوج')}</span><ArrowUpRight size={17}/></p></div></Link>}
export function ProductCard({product:p,lang}:{product:Product;lang:Lang}){return <article className="product-card"><Link href={href(lang,`/products/${p.category}/${p.slug}`)} className="product-photo" aria-label={p.name}>{p.image?<Image src={p.image} alt={p.name} fill sizes="(max-width:680px) 43vw, 290px"/>:<span className="missing-photo"><Package size={35}/>{tr(lang,'Product image on request','صورة المنتج عند الطلب')}</span>}</Link><div className="product-info"><span className="brand-label">{p.brand|| (lang==='ar'?getCategory(p.category)?.ar:getCategory(p.category)?.name)}</span><Link href={href(lang,`/products/${p.category}/${p.slug}`)}><h3 dir="auto">{p.name}</h3></Link><p dir="auto">{p.packSize||p.usageUnit||tr(lang,'Pack details on request','تفاصيل العبوة عند الطلب')}</p><Link href={href(lang,'/request-quote')+'?product='+encodeURIComponent(p.id)} className="textlink">{tr(lang,'Request quote','اطلب عرض سعر')}<Arrow size={15}/></Link></div></article>}
export function Footer({lang}:{lang:Lang}){return <footer className="site-footer"><div className="wrap"><div className="footer-grid"><div><div className="brand"><span className="brand-mark">FAR</span><span className="brand-name">{tr(lang,'FAIZAN AL RABEE','فيضان الربيع')}<small>{tr(lang,'TRADING & DISTRIBUTION','التجارة والتوزيع')}</small></span></div><p>{tr(lang,'Dependable sourcing. Responsive service. A supply partner for your business in Saudi Arabia.','توريد موثوق وخدمة سريعة الاستجابة. شريك توريد لأعمالكم في المملكة العربية السعودية.')}</p></div><div><h3>{tr(lang,'Company','الشركة')}</h3>{[['about','About us','من نحن'],['coverage','Our coverage','نطاق التغطية'],['clients','Client relationships','علاقات العملاء'],['quality','Quality & compliance','الجودة والامتثال']].map(([url,en,ar])=><Link href={href(lang,'/'+url)} key={url}>{tr(lang,en,ar)}</Link>)}</div><div><h3>{tr(lang,'Explore','استكشف')}</h3>{[['products','Product catalogue','كتالوج المنتجات'],['brands','Our brand portfolio','العلامات التجارية'],['industries','Industries we serve','القطاعات التي نخدمها'],['procurement','Procurement & supply','المشتريات والتوريد']].map(([url,en,ar])=><Link href={href(lang,'/'+url)} key={url}>{tr(lang,en,ar)}</Link>)}</div><div><h3>{tr(lang,'Let’s talk supply','لنتحدث عن التوريد')}</h3><a href={'mailto:'+company.email}>{company.email}</a><a href={'tel:'+company.phone} dir="ltr">{company.displayPhone}</a><Link href={href(lang,'/contact')}>{tr(lang,'Riyadh, Saudi Arabia','الرياض، المملكة العربية السعودية')}</Link><Link href={href(lang,'/request-quote')} style={{color:'#e6eac8',marginTop:18}}>{tr(lang,'Send your requirements','أرسل متطلباتك')} ↗</Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {tr(lang,'Faizan Al Rabee Company. All rights reserved.','شركة فيضان الربيع. جميع الحقوق محفوظة.')}</span><div><Link href={href(lang,'/privacy')}>{tr(lang,'Privacy','الخصوصية')}</Link><Link href={href(lang,'/terms')}>{tr(lang,'Terms','الشروط')}</Link><Link href={href(lang,'/cookies')}>{tr(lang,'Cookies','ملفات الارتباط')}</Link></div></div></div></footer>}
export const valueItems=[{icon:Boxes,en:'Reliable sourcing',ar:'توريد موثوق',text:'A broad portfolio, with sourcing support for the requirements beyond it.',arText:'مجموعة واسعة من المنتجات مع دعم لتوريد احتياجاتكم الأخرى.'},{icon:Handshake,en:'Long-term thinking',ar:'شراكات طويلة الأمد',text:'A practical supply relationship built around your business.',arText:'علاقة توريد عملية تتمحور حول احتياجات أعمالكم.'},{icon:Headphones,en:'Responsive service',ar:'خدمة متجاوبة',text:'Clear communication from your first enquiry to your next order.',arText:'تواصل واضح من الاستفسار الأول وحتى الطلب التالي.'},{icon:ShieldCheck,en:'Quality-focused supply',ar:'توريد يركز على الجودة',text:'Product details and documentation discussed before order confirmation.',arText:'مراجعة تفاصيل المنتجات والوثائق قبل تأكيد الطلب.'}];
